export const LANGUAGE_MAP: { [key: string]: string } = {
  javascript: "JavaScript",
  js: "JavaScript",
  typescript: "TypeScript",
  ts: "TypeScript",
  jsx: "JSX",
  tsx: "TSX",
  html: "HTML",
  css: "CSS",
  python: "Python",
  java: "Java",
  cpp: "C++",
  c: "C",
  sql: "SQL",
  bash: "Terminal",
  sh: "Terminal",
  json: "JSON",
  xml: "XML",
  yaml: "YAML",
  yml: "YAML",
  go: "Go",
  rust: "Rust",
  php: "PHP",
  ruby: "Ruby",
  swift: "Swift",
  kotlin: "Kotlin",
  dart: "Dart",
  scala: "Scala",
  r: "R",
  matlab: "MATLAB",
  perl: "Perl",
  lua: "Lua",
  haskell: "Haskell",
  clojure: "Clojure",
  elixir: "Elixir",
  erlang: "Erlang",
  fsharp: "F#",
  ocaml: "OCaml",
  scheme: "Scheme",
  racket: "Racket",
  prolog: "Prolog",
  fortran: "Fortran",
  cobol: "COBOL",
  assembly: "Assembly",
  makefile: "Makefile",
  dockerfile: "Dockerfile",
  nginx: "Nginx",
  apache: "Apache",
  vim: "Vim",
  emacs: "Emacs",
  powershell: "PowerShell",
  batch: "Batch",
  ini: "INI",
  toml: "TOML",
  properties: "Properties",
  gitignore: "Gitignore",
  markdown: "Markdown",
  tex: "LaTeX",
  bibtex: "BibTeX",
  graphql: "GraphQL",
  protobuf: "Protocol Buffers",
  thrift: "Thrift",
  avro: "Avro",
  jsonld: "JSON-LD",
  turtle: "Turtle",
  sparql: "SPARQL",
  cypher: "Cypher",
  gremlin: "Gremlin",
  xpath: "XPath",
  xquery: "XQuery",
  xslt: "XSLT",
  regex: "Regular Expression",
  bnf: "BNF",
  ebnf: "EBNF",
  abnf: "ABNF",
  antlr: "ANTLR",
  lex: "Lex",
  yacc: "Yacc",
  bison: "Bison",
  flex: "Flex",
  code: "Code",
};

export const getLanguageLabel = (language: string): string => {
  return LANGUAGE_MAP[language.toLowerCase()] || language || "Code";
};